# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc27c0e3e7ef62fd6ec033067553c2d4227cb8cc3cf951d6a7dc8c12ad82a7007045e9b99aa50d3e0c48cca046cf3fae5b03f9fc0024bedfbcbdc509b1c0edf

test:
  secret_key_base: 9a2e213c0d2afe279e74f0795cc70f4de9d49baa41df8092726c63e2189224a7756838ab203ad782f4c7b8d6567b1d1daed0963271c27dc70854e53f6462e7ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
